CREATE TABLE IF NOT EXISTS notes
(
    sync_id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    id INTEGER NOT NULL,
    title CHARACTER LARGE OBJECT NOT NULL,
    body CHARACTER LARGE OBJECT NOT NULL,
    folder_id INTEGER NOT NULL,
    tagged_date CHARACTER LARGE OBJECT
);

CREATE TABLE IF NOT EXISTS folders
(
    sync_id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    id INTEGER NOT NULL,
    parent_id INTEGER NOT NULL,
    name CHARACTER LARGE OBJECT NOT NULL
);
